import {game} from './game.js';

var initialGameState = {

  "0": [
    {"type": "buildings", "name": "castle"},
    // {"type": "buildings", "name": "stable", "x": 9, "y": 9},
    // {"type": "buildings", "name": "barrack", "x": 13, "y": 5},
    {"type": "units", "name": "villager", "direction":2},
    // {"type": "units", "name": "militia", "x": 9, "y": 5, "direction": 2},
    // {"type": "units", "name": "knight", "x": 11, "y": 5, "direction": 2},
    // {"type": "units", "name": "direwolf", "x": 13, "y": 5, "direction": 2}
  ],

  "1": [
    {"type": "buildings", "name": "castle"},
    // {"type": "buildings", "name": "stable", "x": 50, "y": 5},
    // {"type": "buildings", "name": "barrack", "x": 55, "y": 10},
    {"type": "units", "name": "villager", "direction":2},
    // {"type": "units", "name": "militia", "x": 52, "y": 3},
    // {"type": "units", "name": "knight", "x": 54, "y": 3},
  ],

  "2": [
    {"type": "buildings", "name": "castle"},
    // {"type": "buildings", "name": "stable", "x": 10, "y": 50},
    // {"type": "buildings", "name": "barrack", "x": 2, "y": 50},
    {"type": "units", "name": "villager", "direction":2},
    // {"type": "units", "name": "militia", "x": 8, "y": 55, "life": 10},
    // {"type": "units", "name": "knight", "x": 10, "y": 55},
    // {"type": "units", "name": "melisandre", "x": 12, "y": 55, "direction": 2}
  ],

  "3": [
    {"type": "buildings", "name": "castle"},
    // {"type": "buildings", "name": "stable", "x": 35, "y": 25},
    // {"type": "buildings", "name": "barrack", "x": 35, "y": 30},
    {"type": "units", "name": "villager", "direction":2},
    // {"type": "units", "name": "militia", "x": 44, "y": 25},
    // {"type": "units", "name": "knight", "x": 46, "y": 25},
  ],

  "4": [
    {"type": "buildings", "name": "castle"},
    // {"type": "buildings", "name": "stable", "x": 70, "y": 47},
    // {"type": "buildings", "name": "barrack", "x": 65, "y": 50},
    {"type": "units", "name": "dragon"},
    {"type": "units", "name": "villager", "direction":2},
    // {"type": "units", "name": "militia", "x": 68, "y": 55},
    // {"type": "units", "name": "knight", "x": 70, "y": 55},
  ],
  "terrains":[
    {"type": "terrains", "name": "forest", "x": 30, "y": 22},
    {"type": "terrains", "name": "forest", "x": 31, "y": 22},
    {"type": "terrains", "name": "forest", "x": 32, "y": 22},
    {"type": "terrains", "name": "forest", "x": 33, "y": 22},
    {"type": "terrains", "name": "forest", "x": 30, "y": 23},
    {"type": "terrains", "name": "forest", "x": 31, "y": 23},
    {"type": "terrains", "name": "forest", "x": 32, "y": 23},
    {"type": "terrains", "name": "forest", "x": 33, "y": 23},
    {"type": "terrains", "name": "forest", "x": 30, "y": 24},
    {"type": "terrains", "name": "forest", "x": 31, "y": 24},
    {"type": "terrains", "name": "forest", "x": 32, "y": 24},
    {"type": "terrains", "name": "forest", "x": 33, "y": 24},
    {"type": "terrains", "name": "forest", "x": 30, "y": 25},
    {"type": "terrains", "name": "forest", "x": 31, "y": 25},
    {"type": "terrains", "name": "forest", "x": 32, "y": 25},
    {"type": "terrains", "name": "forest", "x": 33, "y": 25},
    {"type": "terrains", "name": "forest", "x": 45, "y": 32},
    {"type": "terrains", "name": "forest", "x": 46, "y": 32},
    {"type": "terrains", "name": "forest", "x": 47, "y": 32},
    {"type": "terrains", "name": "forest", "x": 48, "y": 32},
    {"type": "terrains", "name": "forest", "x": 45, "y": 33},
    {"type": "terrains", "name": "forest", "x": 46, "y": 33},
    {"type": "terrains", "name": "forest", "x": 47, "y": 33},
    {"type": "terrains", "name": "forest", "x": 48, "y": 33},
    {"type": "terrains", "name": "forest", "x": 45, "y": 34},
    {"type": "terrains", "name": "forest", "x": 46, "y": 34},
    {"type": "terrains", "name": "forest", "x": 47, "y": 34},
    {"type": "terrains", "name": "forest", "x": 48, "y": 34},
    {"type": "terrains", "name": "forest", "x": 45, "y": 35},
    {"type": "terrains", "name": "forest", "x": 46, "y": 35},
    {"type": "terrains", "name": "forest", "x": 47, "y": 35},
    {"type": "terrains", "name": "forest", "x": 48, "y": 35},
    {"type": "terrains", "name": "field", "x": 45, "y": 22},
    {"type": "terrains", "name": "field", "x": 46, "y": 22},
    {"type": "terrains", "name": "field", "x": 47, "y": 22},
    {"type": "terrains", "name": "field", "x": 48, "y": 22},
    {"type": "terrains", "name": "field", "x": 45, "y": 23},
    {"type": "terrains", "name": "field", "x": 46, "y": 23},
    {"type": "terrains", "name": "field", "x": 47, "y": 23},
    {"type": "terrains", "name": "field", "x": 48, "y": 23},
    {"type": "terrains", "name": "field", "x": 45, "y": 24},
    {"type": "terrains", "name": "field", "x": 46, "y": 24},
    {"type": "terrains", "name": "field", "x": 47, "y": 24},
    {"type": "terrains", "name": "field", "x": 48, "y": 24},
    {"type": "terrains", "name": "field", "x": 45, "y": 25},
    {"type": "terrains", "name": "field", "x": 46, "y": 25},
    {"type": "terrains", "name": "field", "x": 47, "y": 25},
    {"type": "terrains", "name": "field", "x": 48, "y": 25},
    {"type": "terrains", "name": "field", "x": 30, "y": 32},
    {"type": "terrains", "name": "field", "x": 31, "y": 32},
    {"type": "terrains", "name": "field", "x": 32, "y": 32},
    {"type": "terrains", "name": "field", "x": 33, "y": 32},
    {"type": "terrains", "name": "field", "x": 30, "y": 33},
    {"type": "terrains", "name": "field", "x": 31, "y": 33},
    {"type": "terrains", "name": "field", "x": 32, "y": 33},
    {"type": "terrains", "name": "field", "x": 33, "y": 33},
    {"type": "terrains", "name": "field", "x": 30, "y": 34},
    {"type": "terrains", "name": "field", "x": 31, "y": 34},
    {"type": "terrains", "name": "field", "x": 32, "y": 34},
    {"type": "terrains", "name": "field", "x": 33, "y": 34},
    {"type": "terrains", "name": "field", "x": 30, "y": 35},
    {"type": "terrains", "name": "field", "x": 31, "y": 35},
    {"type": "terrains", "name": "field", "x": 32, "y": 35},
    {"type": "terrains", "name": "field", "x": 33, "y": 35},
  ]

}
export {initialGameState};
